### ISSUE TITLE
indeterministic line break?

### ISSUE THREAD

**Issue by skyzh** [ice1000/risingwave-wadler#3]
It seems that the line break result is different on macOS and Ubuntu. Probably we should make it deterministic?

https://github.com/risinglightdb/risinglight/actions/runs/4214830161/jobs/7315545800

**Comment by ice1000** [comment]
I am using `\n`. Could it be the problem of the test framework?

**Comment by skyzh** [comment]
turned out to be an upstream bug 🤣 https://github.com/risinglightdb/risinglight/pull/777
